#!/usr/bin/env bash

source ~/.config/hypr/lib.sh

window="powermenu-window"

current_info=$(eww-rice windows | grep "$window")

if [[ $current_info == "*$window" ]]; then
	eww-rice close $window
else
	eww-rice open $window
fi
