#!/usr/bin/env bash

vlevel=$(./scripts/get_output_volume)

is_muted=$(./scripts/is_output_muted) # yes or no

if [[ $is_muted == "yes" ]]; then
  echo "󰖁"
else
  if (( $vlevel > 49 )); then
    echo "󰕾"
  elif (( $vlevel > 0 )); then
    echo "󰖀"
  else
    echo "󰝟"
  fi
fi
