#!/usr/bin/env bash

if command -v wpctl > /dev/null 2>&1; then
  imwp=$(wpctl get-volume @DEFAULT_SINK@ | grep "MUTED")

  if [[ $imwp == "" ]]; then
    echo "no"
  else
    echo "yes"
  fi
else
  pactl get-sink-mute @DEFAULT_SINK@ | sed 's/Mute: //g'
fi
